import replicate
import os

REPLICATE_API_TOKEN = os.getenv("REPLICATE_API_TOKEN")

def generate_album_cover_art(prompt: str = "a 19th century portrait of a wombat gentleman"):
    """
    This function uses one of the Stable Diffusion models available via Replicate to generate the album cover for a song.
    Args:
        prompt (str): user input that will be given to the model to generate the album/song cover art 
        config (dict): Configuration to be used by the model for genration of song lyrics
    Returns:
        response (str): Link to image output generated by the model hosted by Replicate
    """
    print(REPLICATE_API_TOKEN)
    
    model_name = config["model_name"]
    model_version = config["model_version"]
    model = replicate.models.get(model_name)
    version = model.versions.get(model_version)
    print(prompt, "prompt")
    response = version.predict(prompt = prompt)
    
    return response