import os
import openai
import random

openai.api_key = os.environ.get("OPENAI_API_KEY")


def generate_song_lyrics(inputs: dict, config: dict):
  """
  This function uses one of OpenAI GPT3 model variants to generate lyrics for a song corresponding to user prompt.
  Args:
    inputs (dict): Dictionary containing input items for song lyrics generation such as song genre, artist and prompt text for model to use
    config (dict): Configuration to be used by the model for genration of song lyrics
  Returns:
    response (str): Song lyrics generated by the model
  """
  ## choose artist
  artists = config["genre"]
  artist = random.choice(artists)

  ## create prompt
  prompt_text = f"Below is a {inputs['genre']} song by {artist} about {inputs['text']}.\n\n '{inputs['text']}'\n"
  print(prompt_text)
  
  ## get model prediction
  response = openai.Completion.create(
    engine=config["engine"],
    prompt=prompt_text,
    temperature=config["temperature"],
    max_tokens=config["max_tokens"],
    frequency_penalty=config["frequency_penalty"]
  )
  print(response)
  return response
